name: Build (Linux)

on:
  workflow_dispatch:
    inputs:
      build-type:
        description: Build in Release or Debug?
        required: true
        default: Debug
        type: choice
        options:
          - Debug
          - Release
  workflow_call:
    inputs:
      build-type:
        required: true
        default: Debug
        type: string

jobs:
  Linux:
    name: Build (${{ github.event.inputs.build-type || inputs.build-type }})
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        id: setup
        run: |
          echo "::set-output name=build-type::${{ github.event.inputs.build-type || inputs.build-type }}"
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install build-essential git cmake wget clang ninja-build xorg-dev libdbus-1-dev libssl-dev mesa-utils
          rustup toolchain install nightly
          shards/bootstrap
      - uses: Swatinem/rust-cache@v1
        if: ${{ github.event_name != 'workflow_dispatch' }}
        with:
          sharedKey: Linux-${{ steps.setup.outputs.build-type }}
      - name: Build
        run: |
          cmake --version
          cmake -Bbuild -G Ninja -DCMAKE_BUILD_TYPE=${{ steps.setup.outputs.build-type }}
          cmake --build build --target app
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-ubuntu-${{ steps.setup.outputs.build-type }}
          path: build/app
          if-no-files-found: error
