name: Build (Android)

on:
  workflow_dispatch:
    inputs:
      build-type:
        description: Build in Release or Debug?
        required: true
        default: Debug
        type: choice
        options:
          - Debug
          - Release
  workflow_call:
    inputs:
      build-type:
        required: true
        default: Debug
        type: string

jobs:
  Linux:
    name: Build (${{ github.event.inputs.build-type || inputs.build-type }})
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        id: setup
        run: |
          echo "::set-output name=build-type::${{ github.event.inputs.build-type || inputs.build-type }}"
          if [ "${{ github.event.inputs.build-type || inputs.build-type }}" == "Debug" ]
          then
            echo "::set-output name=apk-artifact::debug/app-debug.apk"
          else
            echo "::set-output name=apk-artifact::release/app-release-unsigned.apk"
          fi
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup SDK
        uses: android-actions/setup-android@v2
      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r23c
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install build-essential git cmake wget clang ninja-build xorg-dev libdbus-1-dev libssl-dev mesa-utils
          shards/bootstrap
          rustup toolchain install nightly
          rustup +nightly target add aarch64-linux-android

          # Override CMake directory for gradle
          echo "cmake.dir=$(which cmake)" >android/local.proprties
      - uses: Swatinem/rust-cache@v1
        if: ${{ github.event_name != 'workflow_dispatch' }}
        with:
          sharedKey: Linux-${{ steps.setup.outputs.build-type }}
      - name: Build
        run: |
          cd android
          chmod +x ./gradlew
          ./gradlew --no-daemon assemble${{ steps.setup.outputs.build-type }}
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-android-arm64-${{ steps.setup.outputs.build-type }}
          path: android/build/outputs/apk/${{ steps.setup.outputs.apk-artifact }}
          if-no-files-found: error
