name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  Linux:
    uses: ./.github/workflows/build-linux.yml
    secrets: inherit
    with:
      build-type: Release
  Windows:
    uses: ./.github/workflows/build-windows.yml
    secrets: inherit
    with:
      bitness: 64bits
      build-type: Release
  iOS:
    uses: ./.github/workflows/build-ios.yml
    secrets: inherit
    with:
      build-type: Debug
  Android:
    uses: ./.github/workflows/build-android.yml
    secrets: inherit
    with:
      build-type: Debug
  macOS:
    uses: ./.github/workflows/build-macos.yml
    secrets: inherit
    with:
      build-type: Debug
